const data = {
  cars: [
    {
      name: "BMW M8",
      image: "/images/cars/bmw_m8.png",
      payPerDay: 305,
      fuelType: "Petrol",
      bookedTimeSlots: "",
      capacity: 5,
    },
    {
      name: "BMW X1",
      image: "/images/cars/bmw_x1.png",
      payPerDay: 300,
      fuelType: "Petrol",
      bookedTimeSlots: "",
      capacity: 5,
    },
    {
      name: "BMW Z4",
      image: "/images/cars/bmw_z4.png",
      payPerDay: 250,
      fuelType: "Diesel",
      bookedTimeSlots: "",
      capacity: 5,
    },
    {
      name: "Ferrari F8",
      image: "/images/cars/ferrari_f8.png",
      payPerDay: 145,
      fuelType: "Petrol",
      bookedTimeSlots: "",
      capacity: 5,
    },
    {
      name: "Ferrari Roma",
      image: "/images/cars/ferrari_roma.png",
      payPerDay: 370,
      fuelType: "Diesel",
      bookedTimeSlots: "",
      capacity: 5,
    },
    {
      name: "Ferrari SF90",
      image: "/images/cars/ferrari_sf90.png",
      payPerDay: 425,
      fuelType: "Petrol",
      bookedTimeSlots: "",
      capacity: 5,
    },
    {
      name: "Mahindra Alturas",
      image: "/images/cars/Mahindra_Alturas.png",
      payPerDay: 285,
      fuelType: "Petrol",
      bookedTimeSlots: "",
      capacity: 5,
    },
    {
      name: "Tesla Cybertruck",
      image: "/images/cars/Tesla_Cybertruck.png",
      payPerDay: 500,
      fuelType: "Electric",
      bookedTimeSlots: "",
      capacity: 5,
    },
    {
      name: "Tesla X",
      image: "/images/cars/tesla_x.png",
      payPerDay: 300,
      fuelType: "Electric",
      bookedTimeSlots: "",
      capacity: 5,
    },
    {
      name: "Thar",
      image: "/images/cars/thar.png",
      payPerDay: 350,
      fuelType: "Petrol/Diesel",
      bookedTimeSlots: "",
      capacity: 5,
    },
  ],
};

export default data;
